data_source postgres_db:
  type: postgres
  connection:
    host: postgres
    port: "5432"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: postgres
    schema: public
